base_url : http://localhost:4000
dev : true
site_url : http://www.pierrebaron.fr
navigation:
- text: HOME
  url: /
- text: BLOG
  url: /blog/
  layout: post
- text: CONTACT
  url: /contact/
subnavigation:
- text: Index
  url: /
- text: Examples
  url: /examples/
  dropdown :
    - text: Basic example
      url: basic/
    - text: Options example
      url: options/
    - text: Full example
      url: full/
    - text: Custom ACE Editor sources
      url: custom/
      label : 1.2.3
- text: Docs
  url: /docs/
sass:
  sass_dir: _sass
  style: :compressed