base_url : http://prbaron.github.io/pbckcode
dev : false
exclude : ['sass']
google_analytics_id: UA-21369110-4
encoding : UTF-8
markdown: rdiscount
pygments: true
site_url : http://www.pierrebaron.fr
navigation:
- text: Index
  url: /
- text: Examples
  url: /examples/
- text: Docs
  url: /docs/