base_url : http://localhost:4000
dev : true
exclude : ['sass']
encoding : UTF-8
markdown: rdiscount
pygments: true
site_url : http://www.pierrebaron.fr
navigation:
- text: Index
  url: /
- text: Examples
  url: /examples/
- text: Docs
  url: /docs/