base_url : http://prbaron.github.io/pbckcode
dev : false
google_analytics_id: UA-21369110-4
encoding : UTF-8
site_url : http://www.pierrebaron.fr
navigation:
- text: HOME
  url: /
- text: BLOG
  url: /blog/
  layout: post
- text: CONTACT
  url: /contact/
subnavigation:
- text: Index
  url: /
- text: Examples
  url: /examples/
- text: Docs
  url: /docs/
sass:
    sass_dir: _sass
    style: :compressed