base_url : http://localhost:4000
dev : false
exclude : ['sass']
encoding : UTF-8
site_url : http://www.pierrebaron.fr
navigation:
- text: HOME
  url: /
- text: BLOG
  url: /blog/
  layout: post
- text: CONTACT
  url: /contact/
subnavigation:
- text: Index
  url: /
- text: Examples
  url: /examples/
  dropdown :
    - text: Basic example
      url: basic/
- text: Docs
  url: /docs/
sass:
    sass_dir: _sass
    style: :compressed

